### PR TITLE
✨Support /themes/ Endpoints

### PR DESCRIPTION
**Pull request by mikemimik**
no issue

- ✨ Added `/themes/{theme-name}/activate` api endpoint
  - Added fixture file for tests
- 🐛 Fixed bug; logical error in `api.themes.upload` where fail fast conditional was being missed

Got some code for us? Awesome 🎊!

Please include a description of your change & check your PR against this list, thanks!

- [x] There's a clear use-case for this code change
- [x] Commit message has a short title & references relevant issues
- [x] The build will pass (run `yarn test` and `yarn lint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by gargol** [comment]
Hey @mikemimik! Another great change ;) Could you please break this PR into 2 separate ones - adding the endpoint and the bugfix? Both are valid changes, happy to merge the bugfix right away. As for endpoint implementation, it also looks good just need to update our list of "stable" [endpoints](https://github.com/TryGhost/Ghost/blob/3.1.1/core/server/web/api/v2/admin/middleware.js#L14-L17) first (it's planned to be done in coming weeks)

**Comment by mikemimik** [comment]
@gargol can do! I'll scope *this* PR into just the bug fix, and I'll open another PR for the api update!

**Comment by gargol** [comment]
Thanks a lot!

**Comment by encadyma** [comment]
Hi @mikemimik @gargol , what is the current progress on this? I would love to use these changes for an automation task I'm writing for Ghost theming. Thanks!

**Comment by gargol** [comment]
@encadyma don't know of any progress that's not publicly visible here. Feel free to take over if you have time on hand :)

**Comment by ErisDS** [comment]
I think it would be better to have this as one commit than not have it at all.

**Pull request merged**
