### PR TITLE
🎨 Add possibility in Tags in gatsby-helpers to return tags without separators

### PR DESCRIPTION
**Pull request by Juuro**
no issue

It was simply not possible to get tags without a separator. Either the default value (", ") was used or, if no separator was specified, an empty span tag was created.

### CODE REVIEW

**Comment by AileenCGN** [comment]
Hey @Juuro 👋 

Thank you very much for the PR. I don't think it makes sense to merge this one, as we want to have the `", "` separator as a default value. See [here](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/helpers-gatsby/src/Tags.js#L16) and [here](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/helpers-gatsby/src/Tags.js#L92). This mirrors the behaviour of our handlebars Tags helper, which you can read about here: https://docs.ghost.org/api/handlebars-themes/helpers/tags/#description

If you wanted to have **no** separator, you can simply pass `separator=""` as a prop. Or, if you'd wanted it separated with a whitespace `separator=" "`. This will work 😄

**Comment by Juuro** [comment]
Hello @AileenCGN ,

thank you for your review. But I have objections.

> If you wanted to have no separator, you can simply pass separator="" as a prop. 

That is what I am doing right now. But if you have a look at the else path [here](https://github.com/TryGhost/Ghost-SDK/blob/master/packages/helpers-gatsby/src/Tags.js#L53) you see that if `props.separator` is an empty string it will still return a `<span>` tag. That tag is empty and right now I use the `separatorClasses` prop to add a class to that `<span>` to be able to `display: none` it. But I think that is a bit ugly. Wouldn't it be much nicer if there exists a possibility to render nothing if someone really doesn't want a separator?

**Comment by AileenCGN** [comment]
@Juuro Thanks a completely valid concern! We have two requirements here:

1. The default separator should always be `", "` if nothing is passed as separator
2. Return an empty `<span>` is indeed ugly and when you pass `separator=""` to prevent falling back to the default one, it should simply not be returned.

Do you want to update your PR to reflect that? Happy to merge it 🤗

**Comment by Juuro** [comment]
@AileenCGN Thank you for opening the PR again. I will have another look at it this week!

**Comment by rishabhgrg** [comment]
👋 Hey @Juuro, just checking in if you'll have some time to pick the PR in coming week(s) for the update, will be good to get this fix in before anyone else trips on it. 😄

**Comment by Juuro** [comment]
Hi @rishabhgrg,

sorry for the delay. 😞 In the week after next week at the latest I will have some time to finally do that. Maybe even at the coming weekend. I definitely didn't forget about it. 🙂

**Comment by Juuro** [comment]
Hey @rishabhgrg @AileenCGN, I think I'm done here and ready for review for now.

**Comment by AileenCGN** [comment]
@Juuro thank you so much for this 🎉! Will try to make some time for this next week 👌🏼

**Comment by AileenCGN** [comment]
@Juuro this works just fine!! Thank you so much, also for adding that many tests 🤗🙏🏼

**Pull request merged**
